INSERT INTO `useraccounts` (`password`,`username`) VALUES ('admin','admin');
INSERT INTO `useraccounts` (`password`,`username`) VALUES ('alum1','alum1');
INSERT INTO `useraccounts` (`password`,`username`) VALUES ('alum2','alum2');
INSERT INTO `useraccounts` (`password`,`username`) VALUES ('alum3','alum3');
INSERT INTO `useraccounts` (`password`,`username`) VALUES ('alum4','alum4');
INSERT INTO `useraccounts` (`password`,`username`) VALUES ('prof1','prof1');
INSERT INTO `useraccounts` (`password`,`username`) VALUES ('prof2','prof2');


INSERT INTO `administradores` (`apellido1`,`apellido2`, `dni`, `email`, `nombre`, `telefono`, `useraccount_id`) VALUES (`Romero`, `Cáceres`, `47542120R`, `antromcac@alum.us.es`,`Antonio`, `955792204`,`1`);


INSERT INTO `cursos` (`nombre`) VALUES ('PRIMERO');
INSERT INTO `cursos` (`nombre`) VALUES ('SEGUNDO');
INSERT INTO `cursos` (`nombre`) VALUES ('TERCERO');
INSERT INTO `cursos` (`nombre`) VALUES ('CUARTO');
INSERT INTO `cursos` (`nombre`) VALUES ('QUINTO');


INSERT INTO `grados` (`nombre`) VALUES ('Ingeniería del Software');
INSERT INTO `grados` (`nombre`) VALUES ('Ingeniería de Computadores');
INSERT INTO `grados` (`nombre`) VALUES ('Tecnología informática');
INSERT INTO `grados` (`nombre`) VALUES ('Administración de Empresas');
INSERT INTO `grados` (`nombre`) VALUES ('Antropología');


INSERT INTO `universidades` (`nombre`) VALUES('Centros dependientes del Ministerio de Defensa');
INSERT INTO `universidades` (`nombre`) VALUES('Centros extranjeros autorizados por la Comunidad Autónoma de Cantabria');
INSERT INTO `universidades` (`nombre`) VALUES('Centros extranjeros autorizados por la Comunidad de Madrid');
INSERT INTO `universidades` (`nombre`) VALUES('CUNEF Universidad');
INSERT INTO `universidades` (`nombre`) VALUES('ESIC Universidad');
INSERT INTO `universidades` (`nombre`) VALUES('IE Universidad');
INSERT INTO `universidades` (`nombre`) VALUES('Mondragón Unibertsitatea');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad a Distancia de Madrid');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Alfonso X El Sabio');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Antonio de Nebrija');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Autónoma de Barcelona');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Autónoma de Madrid');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Camilo José Cela');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Cardenal Herrera-CEU  ');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Carlos III de Madrid ');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Católica de Valencia San Vicente Mártir');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Católica San Antonio');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Católica Santa Teresa de Jesús de Ávila');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Complutense de Madrid');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de A Coruña');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Alcalá');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Alicante');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Almería');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Barcelona');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Burgos');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Cádiz');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Cantabria');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Castilla-La Mancha');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Córdoba');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Deusto');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Extremadura');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Girona');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Granada');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Huelva');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Jaén');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de La Laguna');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de La Rioja');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de las Hespérides');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Las Palmas de Gran Canaria');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de León');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Lleida');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Málaga');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Murcia');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Navarra');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Oviedo');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Salamanca');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Santiago de Compostela');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Sevilla');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Valladolid');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Vic-Universidad Central de Catalunya');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Vigo');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad de Zaragoza');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad del Atlántico Medio');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad del País Vasco/Euskal Herriko Unibertsitatea');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Europea de Canarias');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Europea de Madrid');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Europea del Atlántico');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Europea Miguel de Cervantes');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Fernando Pessoa-Canarias (UFP-C)');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Francisco de Vitoria');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Internacional de Andalucía');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Internacional de La Rioja');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Internacional Isabel I de Castilla');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Internacional Menéndez Pelayo');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Internacional Villanueva');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Jaume I de Castellón');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Loyola Andalucía');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Miguel Hernández de Elche');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Nacional de Educación a Distancia');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Pablo de Olavide');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Politécnica de Cartagena');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Politécnica de Catalunya');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Politécnica de Madrid');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Pompeu Fabra');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Pontificia Comillas');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Pontificia de Salamanca');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Pública de Navarra');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Ramón Llull');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Rey Juan Carlos');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad Rovira i Virgili');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad San Jorge');
INSERT INTO `universidades` (`nombre`) VALUES('Universidad San Pablo-CEU');
INSERT INTO `universidades` (`nombre`) VALUES('Universitat Abat Oliba CEU');
INSERT INTO `universidades` (`nombre`) VALUES('Universitat de les Illes Balears');
INSERT INTO `universidades` (`nombre`) VALUES('Universitat de Valéncia (Estudi General)');
INSERT INTO `universidades` (`nombre`) VALUES('Universitat Internacional de Catalunya');
INSERT INTO `universidades` (`nombre`) VALUES('Universitat Internacional Valenciana');
INSERT INTO `universidades` (`nombre`) VALUES('Universitat Oberta de Catalunya');
INSERT INTO `universidades` (`nombre`) VALUES('Universitat Politécnica de Valéncia');


